### ISSUE TITLE
stock.py 出错

### ISSUE THREAD

**Issue by yangxiaobao87** [DataIntegrationAlliance/data_integration_celery#1]
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{table_name} (wind_code, trade_code, sec_name, ipo_date, delist_date, mkt, exch_' at line 1") [SQL: 'REPLACE INTO {table_name} (wind_code, trade_code, sec_name, ipo_date, delist_date, mkt, exch_city, exch_eng, prename) values (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (('000686.SZ', '000686', '东北证券', '1997-02-27', None, '主板', '深圳', 'SZSE', '锦州六陆;S锦六陆'), ('002293.SZ', '002293', '罗莱生活', '2009-09-10', None, '中小企业板', '深圳', 'SZSE', '罗莱家纺'), ('002171.SZ', '002171', '楚江新材', '2007-09-21', None, '中小企业板', '深圳', 'SZSE', '精诚铜业'), ('603233.SH', '603233', '大参林', '2017-07-31', None, '主板', '上海', 'SSE', None), ('300739.SZ', '300739', '明阳电路', '2018-02-01', None, '创业板', '深圳', 'SZSE', None), ('603056.SH', '603056', '德邦股份', '2018-01-16', None, '主板', '上海', 'SSE', None), ('000807.SZ', '000807', '云铝股份', '1998-04-08', None, '主板', '深圳', 'SZSE', '云铝股份;G云铝'), ('002286.SZ', '002286', '保龄宝', '2009-08-28', None, '中小企业板', '深圳', 'SZSE', None)  ... displaying 10 of 3536 total bound parameter sets ...  ('603889.SH', '603889', '新澳股份', '2014-12-31', None, '主板', '上海', 'SSE', None), ('300290.SZ', '300290', '荣科科技', '2012-02-16', None, '创业板', '深圳', 'SZSE', None))] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by mmmaaaggg** [comment]
已经修复
